<a href="https://colab.research.google.com/github/Mer9ury/vts/blob/main/conference_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
%cd /content/drive/MyDrive/21-1_ybigta/

/content/drive/MyDrive/21-1_ybigta


In [22]:
import json
import pandas as pd
import numpy as np
import sys
from glob import glob

#sys.path.append('/content/gdrive/MyDrive/21-1_ybigta')

sys.path.insert(0,'/content/gdrive/MyDrive/21-1_ybigta')

In [23]:
#!pip install transformers

#멜론 태그


---



In [25]:
music_df = pd.read_json('train.json')
music_df.head(20)

tags  ...                updt_date
0                                                 [락]  ...  2013-12-19 18:36:19.000
1                                            [추억, 회상]  ...  2014-12-02 16:19:42.000
2                                           [까페, 잔잔한]  ...  2017-08-28 07:09:34.000
3   [연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...  ...  2019-12-05 15:15:18.000
4                                                [댄스]  ...  2011-10-25 13:54:56.000
5   [운동, 드라이브, Pop, 트로피컬하우스, 힐링, 기분전환, 2017, 팝, 트렌...  ...  2017-09-15 15:59:26.000
6                         [짝사랑, 취향저격, 슬픔, 고백, 사랑, 이별]  ...  2016-10-24 21:30:17.000
7                                       [잔잔한, 추억, 회상]  ...  2008-09-23 22:32:02.000
8                         [일렉트로니카, 포크, 메탈, 락, 댄스, 인디]  ...  2019-11-30 21:17:59.000
9                  [록, Metal, 이일우, M에센셜, 메탈, Rock, 락]  ...  2016-06-17 18:23:54.000
10                          [kpop, 댄스, 걸그룹댄스, 스트레스해소]  ...  2020-04-13 23:36:55.000
11   [새해, 여행, 프로필음악, 카카오톡, 기분전환, 소원, 프로필, 소망, 다짐, 카톡]  ...  2017-02-16 15:45:23.000
12                               [듣고, 우울, 힐링, 이거, 힘내]  ...  2018-01-04 22:49:29.000
13       [힙합, 느낌있는, 밤, 새벽, RnB, 감각적인, 드라이브, 국내, 그루브한]  ...  2018-01-09 14:01:53.000
14                                           [가을, 재즈]  ...  2017-08-25 22:38:40.000
15                                                [락]  ...  2013-10-17 11:59:02.000
16                           [감성, 질리지않는, 나만알고싶은, Pop]  ...  2018-01-02 12:10:59.000
17                                        [봄, 설렘, 사랑]  ...  2016-03-17 21:50:16.000
18                                    [비오는날, 누군가생각날때]  ...  2016-10-12 16:22:17.000
19                             [스밍, 목록, 폐막식, 올림픽, 엑소]  ...  2018-02-26 10:03:14.000

[20 rows x 6 columns]

In [26]:
tags = set()

for tag_list in music_df['tags']:
    tags.update(tag_list)

In [27]:
tags, len(tags)

({'',
  '현대적인',
  '이소설을다시써보려해',
  '신세계',
  '라라랜드속재즈',
  '포차',
  'JRock',
  'Justice',
  '너무너무너무',
  '따듯한날',
  '그때그감성',
  '매장음악best',
  '혼자있을때듣기좋은노래',
  '가벼운발걸음',
  '유로비트',
  '프롬공연',
  '야너두',
  'CF배경음악',
  '여름과가을사이',
  '아트무비',
  '9명의천사',
  '이천원',
  '신스팝밴드',
  '원스로_가는_길',
  '최순실',
  '마음껏_울어요',
  '비긴어게인',
  '비포미드나잇',
  '너의',
  '미스터포터',
  '니은',
  '괜찮은음악',
  '항상',
  '비노래',
  '애절한',
  '적적',
  '눈물겨운노래',
  '커크해밋',
  '마이웨이',
  '불금토',
  '헌사곡',
  '펍음악',
  '여름노래모음집',
  '프롬콘서트',
  '애기',
  '익숙함',
  'LilWayne',
  '후회없는플레이',
  '차안에서들을곡들',
  '띵곡_모음',
  'MCA',
  '채널',
  '매홀',
  '200217',
  '드럼엔베이스',
  '처절한',
  '올림픽체조경기장',
  '슬럼프',
  'SejongSoloists',
  '세렝게티',
  '고애신',
  '기다리며듣는인기클래식',
  '클릭비',
  '졸업장',
  '세대초월',
  '노동자',
  'RADMUSEUM',
  '무미건조',
  '근로자의날',
  '밤하늘을보다',
  'bruno',
  '힘내',
  '길',
  '피터팬콤플렉스',
  '섬머쏭',
  '오월의황금연휴와',
  '두달뒤에',
  '바람핀남친',
  'dsp미디어',
  '헬스할때',
  '트니트니',
  'umfkorea2018umf',
  '상큼하고',
  '90년대생',
  '오리엔트기획',
  '숨어듣는명곡',
  '뉴그래스',
  '생각나는사람',
  '행복하세요',
  '봄쿠스틱',
  '가을웜톤',
  '특

In [28]:
!ls

caption       conference.ipynb	   song_meta.json	textrank
caption.json  music_tags_old.json  test_1_caption.json	train.json


In [29]:
song_df = pd.read_json('song_meta.json')

In [30]:
song_df.head(20)

song_gn_dtl_gnr_basket  ...  id
0                                   [GN0901]  ...   0
1                           [GN1601, GN1606]  ...   1
2                                   [GN0901]  ...   2
3                           [GN1102, GN1101]  ...   3
4                           [GN1802, GN1801]  ...   4
5                                   [GN1701]  ...   5
6                   [GN1601, GN1602, GN1614]  ...   6
7                   [GN1601, GN1602, GN1614]  ...   7
8                                   [GN0301]  ...   8
9                           [GN0105, GN0101]  ...   9
10                                  [GN1201]  ...  10
11                                  [GN1301]  ...  11
12                                  [GN1701]  ...  12
13                          [GN1701, GN1703]  ...  13
14          [GN2704, GN1104, GN1103, GN1101]  ...  14
15                          [GN1601, GN1613]  ...  15
16                                  [GN0901]  ...  16
17  [GN2503, GN0205, GN2501, GN2506, GN0201]  ...  17
18                          [GN2805, GN2801]  ...  18
19  [GN0805, GN0501, GN0502, GN0801, GN0509]  ...  19

[20 rows x 9 columns]

In [31]:
song_df.shape

(707989, 9)

In [145]:
song_df.iloc[257155]

song_gn_dtl_gnr_basket    [GN1402, GN1401, GN1407]
issue_date                                20190627
album_name                            Some Comfort
album_id                                  10300568
artist_id_basket                           [50513]
song_name                             Some Comfort
song_gn_gnr_basket                        [GN1400]
artist_name_basket              [Kevin Montgomery]
id                                          257155
Name: 257155, dtype: object

#captioning 


---



In [33]:
 json_files = glob('./caption/test*.json')

In [34]:
json_dic = {}

for json_file in json_files:
    #print(json_file)
    df = pd.read_json(json_file)
    json_dic[json_file]=df

TEXT 만들기

---

sentences : 영어 문장 리스트가 딕셔너리 형태로 저장되어 있음

korean sentences : 한국어로 번역한 문장 리스트가 딕셔너리 형태로 저장되어 있음

In [35]:
!pip install google_trans_new
from google_trans_new import google_translator  
translator = google_translator() 

In [36]:
sentences = {}
korean_sentences = {}
for json_file in json_files:
    sentence = []
    korean = []
    for text in json_dic[json_file]['sentence']:
        sentence.append(text+'.')
        # en_to_jp = translator.translate(text+'. ', lang_src='en', lang_tgt='jp') 
        en_to_ko = translator.translate(text+'. ', lang_src='en', lang_tgt='ko') #영어를 한국어로
        korean.append(en_to_ko)

    sentences[json_file[10:-5]] = sentence
    korean_sentences[json_file[10:-5]] = korean

#Kobert tokenizer

---

captioning된 문장이랑 멜론의 태그랑 비슷해보이는게 없더구먼요..

벡터라이즈를 해야하나 싶습니다.

In [37]:
#!pip install git+https://github.com/monologg/KoBERT-Transformers.git

In [38]:
#!pip3 install kobert-transformers

In [39]:

#tokenizer.convert_tokens_to_ids()

In [40]:
# from kobert_transformers import get_tokenizer
# #(komoran_words['test_10_caption'])#.split('/')

# new_words = []
# for word, rank in komoran_words['test_10_caption']:
#     word_split = word.split('/')
#     new_words.append(word_split[0])

In [41]:
# tokenizer = get_tokenizer()
# tokenizer.convert_tokens_to_ids(new_words)


In [42]:
# tokens = tokenizer.tokenize(korean_sentences['test_10_caption'][0])

In [43]:
# tokenizer.convert_tokens_to_ids(tokens)

#Pytextrank with spacy 

---


```
!pip install pytextrank
!pip install --upgrade spacy
!python -m spacy download en_core_web_sm

import spacy
import pytextrank

# example text
text = "Compatibility of systems of linear constraints over the set of natural numbers. Criteria of compatibility of a system of linear Diophantine equations, strict inequations, and nonstrict inequations are considered. Upper bounds for components of a minimal set of solutions and algorithms of construction of minimal generating sets of solutions for all types of systems are given. These criteria and the corresponding algorithms for constructing a minimal supporting set of solutions can be used in solving all the considered types systems and systems of mixed types."

# load a spaCy model, depending on language, scale, etc.
nlp = spacy.load("en_core_web_sm")

# add PyTextRank to the spaCy pipeline
nlp.add_pipe("textrank")
doc = nlp(sentence)

# examine the top-ranked phrases in the document
for phrase in doc._.phrases:
    print(phrase.text)
    print(phrase.rank, phrase.count)
    print(phrase.chunks)

```




In [44]:
!pip install pytextrank
!pip install --upgrade spacy
!python -m spacy download en_core_web_sm
!pip install ordered-set
from ordered_set import OrderedSet
import spacy
import pytextrank

     |████████████████████████████████| 12.8MB 11.3MB/s 
     |████████████████████████████████| 624kB 49.9MB/s 
     |████████████████████████████████| 51kB 8.8MB/s 
     |████████████████████████████████| 9.1MB 56.8MB/s 
     |████████████████████████████████| 460kB 47.5MB/s 
     |████████████████████████████████| 122kB 71.8MB/s 
  Created wheel for smart-open: filename=smart_open-3.0.0-cp37-none-any.whl size=107107 sha256=b5a5cf6168f8e775b1e2072b649fc69d42620056305cc8d32b13f54d3b5a1fb1
  Stored in directory: /root/.cache/pip/wheels/18/88/7c/f06dabd5e9cabe02d2269167bcacbbf9b47d0c0ff7d6ebcb78
Successfully built smart-open
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
  Found existing installation: catalogue 1.0.0
    Uninstalling catalogue-1.0.0:
      Successfully uninstalled catalogue-1.0.0
  Found existing installation: srsly 1.0.5
    Uninstalling srsly-1.0.5:
      Successfully uninstalled srsly-1.

In [45]:
# example text
#text = "Compatibility of systems of linear constraints over the set of natural numbers. Criteria of compatibility of a system of linear Diophantine equations, strict inequations, and nonstrict inequations are considered. Upper bounds for components of a minimal set of solutions and algorithms of construction of minimal generating sets of solutions for all types of systems are given. These criteria and the corresponding algorithms for constructing a minimal supporting set of solutions can be used in solving all the considered types systems and systems of mixed types."

# load a spaCy model, depending on language, scale, etc.
nlp = spacy.load("en_core_web_sm")

# add PyTextRank to the spaCy pipeline
#nlp.add_pipe("textrank")
nlp.add_pipe("textrank", config={ "stopwords": { "A woman": ["NOUN"] , "woman": ["NOUN"] , "the woman": ["NOUN"] , "women": ["NOUN"] ,"a woman": ["NOUN"] , "men": ["NOUN"] , "the man": ["NOUN"] ,"A man": ["NOUN"] ,"a man": ["NOUN"] , "they": ["NOUN"]} })
spacy_words = {}
for json_file in json_files:

    text = ''.join(sentences[json_file[10:-5]])
    print('='*30)
    print(json_file[10:-5])
    print(text)
    doc = nlp(text)
    print('')

    # examine the top-ranked phrases in the document
    word_list = []
    for phrase in doc._.phrases:
        print(phrase.text)
        word_list.append(phrase.text)
    spacy_words[json_file[10:-5]]=word_list
        #print(phrase.rank, phrase.count)
        #print(phrase.chunks)


test_22_caption
A woman is sitting on a chair with a woman in a white shirt and a white shirt is sitting on a table.A man is sitting on a chair with a little girl in her hand.A man and a woman are sitting in a chair with a baby and talking to the camera.A woman is sitting on a chair.A man is seen sitting on a table with a child holding a baby and holding a baby and holding a baby and holding a baby.The boy and the child are playing with the child.A woman is sitting in a chair with a baby and talking to the camera.A woman is sitting on a chair.A woman is sitting on a chair.A baby is sitting on a chair.A young boy is sitting on a chair with a baby in his hand.A group of people are sitting on a table with a woman sitting on a table.A woman is sitting on a chair.A man is seen sitting on a chair with a baby and holding a baby and holding a baby.The lady puts her hand on the floor.A woman is seen sitting on a table with a woman sitting on a table with a woman sitting on a table and holding a

In [46]:
json_dic['./caption/test_27_caption.json']

start    end                                           sentence
0     1.3   31.6  A woman is seen standing in a room holding a c...
1     0.0   10.1  A woman is seen standing in front of a camera ...
2    80.8  104.7  A man is seen standing on a wall and leads int...
3     0.0  146.4  A young man is seen speaking to the camera and...
4   225.2  261.4  A woman is seen sitting on a chair with a woma...
5    36.1   68.4  A man is seen standing in a room holding a cam...
6   159.9  198.1  A man is seen speaking to the camera while hol...
7     1.0    4.5     A man in a blue shirt is standing on the table
8   185.6  224.4  The woman is talking to the camera and a woman...
9    95.6  106.0                The man in the red shirt walks away
10  137.4  176.3  A man is seen sitting in a chair and speaking ...
11   96.4  136.7  A man is seen standing in front of a camera an...
12  248.3  261.6  A man is seen sitting on a chair and begins to...
13   43.7  102.1  A man is seen sitting on a chair and looking a...
14  116.9  160.3  A man is seen speaking to the camera while hol...
15   16.6   46.7  A man is seen speaking to the camera while hol...
16    0.0    1.9     A man in a blue shirt is standing on the table
17   62.0   83.8  A man is seen sitting on a chair and leads int...

In [47]:
korean_tags={}
stop_words = ["A woman","woman",'the woman','women','a woman','a man','A man','man','the man','men','they']
    
for json_file in json_files:
    text = ''
    for word in spacy_words[json_file[10:-5]]:
        if word not in stop_words:
            text+=word+', '

    en_to_ko = translator.translate(text[:-2], lang_src='en', lang_tgt='ko')
    letters = OrderedSet(en_to_ko.split(', '))

    korean_tags[json_file[10:-5]] = list(letters)

In [48]:
final_tags = {}

for json_file in json_files:
    letters = [] 
    for word in korean_tags[json_file[10:-5]]:
        if '자동차'==word:
            letters.append('드라이브')
        elif '차'==word:
            if 'tea' not in ' '.join(spacy_words[json_file[10:-5]]):
                letters.append('드라이브')
        elif '거리' ==word:
            letters.append('산책')
            letters.append('일상')
        elif '바다' ==word:
            letters.append('휴양지')
            letters.append('여행')
            letters.append('청량한')
        elif word in ['그릇','음식']:
            letters.append('요리')
            letters.append('레스토랑')
        elif word in ['개','강아지','고양이']:
            letters.append('반려동물')
            letters.append('힐링')
        elif word in ['피아노', '바이올린']:
            letters.append(word)
        elif word in ['탁구', '공','축구','농구','배드민턴','테니스','라켓']:
            letters.append('운동')
    letters+=korean_tags[json_file[10:-5]]
    final_tags[json_file[10:-5]]=letters

In [49]:
for json_file in json_files:
    print(json_file)
    print(final_tags[json_file[10:-5]])


./caption/test_22_caption.json
['흰색 아기', '아기', '아이스크림', '아이', '흰색 셔츠', '카메라', '사람', '테이블', '바닥', '의자', '어린 소녀', '손', '어린 소년', '소년', '그룹', '아가씨', '남자 ']
./caption/test_30_caption.json
['사람', '앞', '카메라', '넓은 지역', '큰 건물', '큰 그룹', '음료', '큰 해변', '색소폰', '마이크', '테이블', '지붕', '강', '그녀의 손', '무대', '의자', '여자 ']
./caption/test_16_caption.json
['거울', '칼', '하얀 방', '흰색 천', '흰색 고양이', '검은 셔츠', '카메라', '방', '면도기', '소파', '진공', '침대', '의자', '사람', '그에게 ']
./caption/test_28_caption.json
['요리', '레스토랑', '드라이브', '음식', '커피', '카메라', '흰 셔츠', '병', '칼', '테이블', '의자', '차', '그를 ']
./caption/test_18_caption.json
['요리', '레스토랑', '미소', '하얀 접시', '음식', '흰색 컵', '남자', '두 남자', '카메라', '접시', '그녀의 손', '손', '테이블', '검은 셔츠', '어린 소년', '음식 ', '주방', '감자', '카운터', '아이', '소파', '의자', '레몬', '레이디', '둘', '그 ']
./caption/test_13_caption.json
['종이', '테이블', '카메라', '흰색 단어', '아기', '어린 아이', '어린 소년', '의자', '어린 소녀', '아이', '그녀의 무릎', '조각', '소파', '그것 ']
./caption/test_21_caption.json
['피아노', '앞면', '사람들', '젊은 남자', '검은 옷 춤', '무대', '아이', '남자', '검은 셔츠', '방', '


#Textrank Korean


---



```
!pip install Konlpy

from textrank import KeywordSummarizer
#from transformers import BertTokenizer
from konlpy.tag import Komoran

komoran = Komoran()
def komoran_tokenizer(sent):
    words = komoran.pos(sent, join=True)
    words = [w for w in words if ('/NN' in w or '/XR' in w or '/VA' in w or '/VV' in w)]
    return words

summarizer = KeywordSummarizer(tokenize=komoran_tokenizer, min_count=2, min_cooccurrence=1)
summarizer.summarize(sents, topk=20)
```



---





In [50]:
!pip install git+https://github.com/lovit/textrank.git
!pip install Konlpy

  Cloning https://github.com/lovit/textrank.git to /tmp/pip-req-build-_je6w91i
  Running command git clone -q https://github.com/lovit/textrank.git /tmp/pip-req-build-_je6w91i
  Created wheel for textrank: filename=textrank-0.1.2-cp37-none-any.whl size=11170 sha256=e44917e534bfd90017d33cf7a19594a53c7eee210d9f47167a70a3282a9f8729
  Stored in directory: /tmp/pip-ephem-wheel-cache-5970s00r/wheels/e7/9c/0a/8903ddd1a7d41c09ce5cf5476c86a53ee7d1cf50378619e4b8
Successfully built textrank
     |████████████████████████████████| 19.4MB 294kB/s 
     |████████████████████████████████| 92kB 11.5MB/s 
     |████████████████████████████████| 450kB 40.8MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [51]:
from textrank import KeywordSummarizer
from konlpy.tag import Komoran
from konlpy.tag import Okt  
okt=Okt()  

komoran = Komoran()


In [52]:
def komoran_tokenizer(sent):
    words = komoran.pos(sent, join=True)
    words = [w for w in words if (('/NN' in w) and '여자' not in w and '남자' not in w and '앉' not in w and '얼굴' not in w and 'NNB' not in w and 'NNP' not in w)]#or '/XR' in w or '/VA' in w or '/VV' in w)]
    
    return words

In [53]:
summarizer = KeywordSummarizer(tokenize=komoran_tokenizer, min_count=2, min_cooccurrence=1)
komoran_words={}
for json_file in json_files:
    sents = korean_sentences[json_file[10:-5]]
    komoran_words[json_file[10:-5]]=(summarizer.summarize(sents, topk=50))

In [54]:
caption_words={}

for json_file in json_files:
    new_words=[]
    for word, rank in komoran_words[json_file[10:-5]]:
        word_split = word.split('/')
        new_words.append(word_split[0])
    caption_words[json_file[10:-5]]=new_words

In [55]:
caption_words['test_27_caption']

['카메라', '말', '인도', '의자', '병', '동안', '앞', '방', '이야기', '파란색']

In [56]:
caption_tags = {}

for json_file in json_files:
    letters = [] 
    
    for word in caption_words[json_file[10:-5]]:

        if '자동차'==word:
            letters.append('드라이브')
        elif '차'==word:
            if 'tea' not in ' '.join(spacy_words[json_file[10:-5]]):
                letters.append('드라이브')
        elif '거리' ==word:
            letters.append('산책')
            letters.append('일상')
        elif '바다' ==word:
            letters.append('휴양지')
            letters.append('여행')
            letters.append('청량한')
        elif word in ['그릇','음식']:
            letters.append('요리')
            letters.append('레스토랑')
        elif word in ['개','강아지','고양이']:
            letters.append('반려동물')
            letters.append('힐링')
        elif word in ['피아노', '바이올린']:
            letters.append(word)
        elif word in ['운동','탁구', '공','축구','농구','배드민턴','테니스','라켓']:
            letters.append('운동')
        elif word =='카메라':
            letters.append('브이로그')
        elif word=='춤':
            letters.append('내적댄스')
            letters.append('신나는')
            letters.append('기분전환')
    letters+=caption_words[json_file[10:-5]]
    caption_tags[json_file[10:-5]]=letters

In [57]:
for j in json_files:
    print(j[10:-5])
    print(caption_tags[j[10:-5]])
    print('-'*40)

test_22_caption
['브이로그', '아기', '아이', '의자', '이야기', '카메라', '손', '바닥']
----------------------------------------
test_30_caption
['브이로그', '사람', '주위', '말', '카메라', '강', '지역', '그룹', '무대', '표시', '손']
----------------------------------------
test_16_caption
['브이로그', '카메라', '방', '칼', '이야기', '말', '흰색', '사람']
----------------------------------------
test_28_caption
['브이로그', '카메라', '의자', '병', '말', '이야기']
----------------------------------------
test_18_caption
['브이로그', '요리', '레스토랑', '카메라', '흰색', '손', '컵', '이야기', '미소', '말', '음식', '부엌', '감자']
----------------------------------------
test_13_caption
['브이로그', '아기', '이야기', '카메라', '아이']
----------------------------------------
test_21_caption
['내적댄스', '신나는', '기분전환', '춤', '방', '무대', '그룹', '앞', '시작', '사람', '동안', '연주']
----------------------------------------
test_17_caption
['요리', '레스토랑', '숟가락', '음식', '부엌']
----------------------------------------
test_29_caption
['반려동물', '힐링', '브이로그', '사람', '고양이', '마무리', '카메라', '흰색', '바닥', '때', '단어', '무릎']
---------------

#Sentence embedding을 해보아요

---



In [58]:
!pip install git+https://github.com/UKPLab/sentence-transformers.git

  Cloning https://github.com/UKPLab/sentence-transformers.git to /tmp/pip-req-build-dun8i7st
  Running command git clone -q https://github.com/UKPLab/sentence-transformers.git /tmp/pip-req-build-dun8i7st
     |████████████████████████████████| 2.5MB 8.0MB/s 
     |████████████████████████████████| 1.2MB 56.9MB/s 
     |████████████████████████████████| 3.3MB 57.4MB/s 
     |████████████████████████████████| 901kB 39.8MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.0.0-cp37-none-any.whl size=130456 sha256=e75602964e62627d400ced499898d8aaf3c4fdfbb63822e517b4cc4bd0b1cf72
  Stored in directory: /tmp/pip-ephem-wheel-cache-49aee_rb/wheels/d9/cc/f0/6fd55568c90df0352de7c25a4b02f8c64c2393df6944cd39eb
Successfully built sentence-transformers


In [59]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

In [60]:
emb_sents = {}
for json_file in json_files:
    sents = sentences[json_file[10:-5]]
    sentence_embeddings = model.encode(sents)
    emb_sents[json_file[10:-5]] = sentence_embeddings

In [61]:
for json_file in json_files:

    for sentence, embedding in zip(sentences[json_file[10:-5]], emb_sents[json_file[10:-5]]):
        print("Sentence:", sentence)
        print("Embedding:", embedding)
        print("")

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  1.52994450e-02 -8.40513185e-02 -2.94182628e-01 -1.76639423e-01
 -5.69489896e-01  2.01475084e-01  1.72698438e-01  4.83486131e-02
 -3.52954380e-02 -4.63109761e-02  6.26304820e-02 -5.26495948e-02
 -9.74781588e-02 -2.94025302e-01 -5.75176418e-01  5.46942465e-02
 -3.27888057e-02 -1.05551936e-01  5.80528378e-01 -5.96751273e-01
  6.04213715e-01 -1.70022875e-01  3.56580347e-01 -3.93434644e-01
  3.01222861e-01 -8.50213692e-02 -4.74027693e-01 -1.29535019e-01
 -1.91333324e-01  2.56722361e-01  4.99469250e-01  9.88117084e-02
 -2.09078282e-01 -3.64065349e-01 -6.32323623e-01  9.83314589e-02
  1.57721918e-02 -3.75397682e-01  7.90771365e-01 -8.26310962e-02
 -7.67624974e-01  1.18911192e-01  3.55348736e-01  6.88881800e-02
 -2.00228482e-01 -1.28876090e+00 -1.96999703e-02  2.26718649e-01
 -5.77418625e-01  3.35620821e-01  4.54663128e-01 -2.20180944e-01
  1.11237668e-01  4.84460801e-01  4.87719923e-01  2.14727789e-01
  2.21900463e-01 -3.86784039e-02 -6.97314084e-01 -7.33

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [62]:
emb_sents[json_file[10:-5]].shape

(9, 384)

#KMEANS clustering

---

sentence embedding 으로는 faiss.Kmeans를 사용했고,


start, end 구간으로는 sklearn.KMeans를 사용하였습니다. 

결과는.......그냥..그냥 그래요 ㅎ..

---

json_dic의 각 데이터 프레임에 cluster결과를 sentence, time별로 입력해두었습니다.



In [63]:
startend={}
for json_file in json_files:
    products_list = json_dic[json_file][['start','end']].values
    startend[json_file[10:-5]]=products_list

SENTENCE KMEANS CLUSTERING : faiss

In [64]:
!pip uninstall faiss-cpu
!pip install faiss
!pip install faiss-cpu

     |████████████████████████████████| 4.7MB 8.3MB/s 
     |████████████████████████████████| 8.4MB 8.4MB/s 


In [65]:
!apt install libomp-dev
!python -m pip install --upgrade faiss faiss-gpu
import faiss

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libomp5
Suggested packages:
  libomp-doc
The following NEW packages will be installed:
  libomp-dev libomp5
0 upgraded, 2 newly installed, 0 to remove and 39 not upgraded.
Need to get 239 kB of archives.
After this operation, 804 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp5 amd64 5.0.1-1 [234 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp-dev amd64 5.0.1-1 [5,088 B]
Fetched 239 kB in 1s (238 kB/s)
Selecting previously unselected package libomp5:amd64.
(Reading database ... 160772 files and directories currently installed.)
Preparing to unpack .../libomp5_5.0.1-1_amd64.deb ...
Unpacking libomp5:amd64 (5.0.1-1) ...
Selecting previously unselected package libomp-dev.
Preparing to unpack .../libomp-dev_5.0.1-1_amd64.deb ...
Unpacking libomp-dev (5.0.1-

In [66]:
import numpy as np
import faiss

# class FaissKMeans:
#     def __init__(self, n_clusters=10, n_init=100, max_iter=300):
#         self.n_clusters = n_clusters
#         self.n_init = n_init
#         self.max_iter = max_iter
#         self.kmeans = None
#         self.cluster_centers_ = None
#         self.inertia_ = None

#     def fit(self, X, y):
#         self.kmeans = faiss.Kmeans(d=X.shape[1],
#                                    k=self.n_clusters,
#                                    niter=self.max_iter,
#                                    nredo=self.n_init)
#         self.kmeans.train(X.astype(np.float32))
#         self.cluster_centers_ = self.kmeans.centroids
#         self.inertia_ = self.kmeans.obj[-1]

#     def predict(self, X):
#         return self.kmeans.index.search(X.astype(np.float32), 1)[1]

In [67]:
kmeans_sentence_dic={}
outputs_sentence_dic={}
for json_file in json_files:
    km={}
    D= 384
    N = int(len(emb_sents[json_file[10:-5]]))
    K = int(len(emb_sents[json_file[10:-5]])/4)  # The number of clusters
    X = emb_sents[json_file[10:-5]]
    print(json_file[10:-5], N)
    # Setup
    kmeans = faiss.Kmeans(d=D, k=K, niter=5, verbose=True)
    # For GPU(s), run the following line. This will use all GPUs
    # kmeans = faiss.Kmeans(d=D, k=K, niter=20, verbose=True, gpu=True)

    # Run clustering
    kmeans.train(X)
    
    # Error for each iteration
    print('error?',kmeans.obj)  # array with 20 elements

    # Centroids after clustering
    print('centeroids', kmeans.centroids.shape)  # (10, 128)

    # The assignment for each vector.
    dists, ids = kmeans.index.search(X, 1)  # Need to run NN search again
    print('ids shape',ids.shape)  # (10000, 1)
    outputs = (ids.flatten())
    # Params
    print("D:", kmeans.d)
    print("K:", kmeans.k)
    print("niter:", kmeans.cp.niter)
    
    for i in outputs:
        km[i]=[] #initialize


    for i in range(len(outputs)):
        km[outputs[i]].append(korean_sentences[json_file[10:-5]][i])
    kmeans_sentence_dic[json_file[10:-5]]=km
    outputs_sentence_dic[json_file[10:-5]]=outputs

test_22_caption 20
error? [415.32937622 250.42390442 214.45352173 205.83612061 205.83612061]
centeroids (5, 384)
ids shape (20, 1)
D: 384
K: 5
niter: 5
test_30_caption 24
error? [385.9576416  241.14590454 203.62130737 203.62130737 203.62130737]
centeroids (6, 384)
ids shape (24, 1)
D: 384
K: 6
niter: 5
test_16_caption 13
error? [257.722229   161.51873779 161.51873779 161.51873779 161.51873779]
centeroids (3, 384)
ids shape (13, 1)
D: 384
K: 3
niter: 5
test_28_caption 11
error? [251.12796021 152.32302856 131.63752747 119.04821777 105.12149048]
centeroids (2, 384)
ids shape (11, 1)
D: 384
K: 2
niter: 5
test_18_caption 32
error? [463.5458374  291.01443481 287.09246826 287.09246826 287.09246826]
centeroids (8, 384)
ids shape (32, 1)
D: 384
K: 8
niter: 5
test_13_caption 12
error? [305.30297852 148.9400177  148.9400177  148.9400177  148.9400177 ]
centeroids (3, 384)
ids shape (12, 1)
D: 384
K: 3
niter: 5
test_21_caption 18
error? [367.92132568 240.01855469 240.01855469 240.01855469 240.01855

 

---



START_END KMEANS CLUSTERING



---



In [68]:
kmeans_dic={}
outputs_dic={}
from sklearn.cluster import KMeans
for json_file in json_files:
    km={}
    D= 2
    N = int(len(startend[json_file[10:-5]]))
    K = int(len(startend[json_file[10:-5]])/4)  # The number of clusters
    X = startend[json_file[10:-5]]

    print(json_file[10:-5], N)
    # Setup
    kmeans = KMeans(n_clusters=K)
    # For GPU(s), run the following line. This will use all GPUs
    # kmeans = faiss.Kmeans(d=D, k=K, niter=20, verbose=True, gpu=True)

    # Run clustering
    kmeans.fit(X)
    
    print(kmeans.labels_)
    outputs = kmeans.labels_
    for i in outputs:
        km[i]=[] #initialize


    for i in range(len(outputs)):
        km[outputs[i]].append(korean_sentences[json_file[10:-5]][i])
    kmeans_dic[json_file[10:-5]]=km
    outputs_dic[json_file[10:-5]]=outputs

test_22_caption 20
[4 1 2 4 0 0 3 4 4 3 1 4 4 2 2 2 0 0 3 1]
test_30_caption 24
[2 1 4 2 3 3 1 2 0 1 1 2 2 3 5 2 1 5 1 1 3 2 5 3]
test_16_caption 13
[0 0 0 2 1 0 2 1 0 2 1 1 2]
test_28_caption 11
[0 0 0 0 0 0 1 0 0 1 0]
test_18_caption 32
[6 5 5 3 2 5 1 2 2 2 5 4 4 2 4 1 0 4 3 4 2 7 7 4 3 3 4 3 2 5 3 7]
test_13_caption 12
[2 2 2 0 2 0 0 1 0 1 2 0]
test_21_caption 18
[1 1 3 3 1 2 1 1 0 0 1 2 2 2 0 0 1 2]
test_17_caption 20
[1 3 4 2 1 1 1 3 4 2 4 1 3 1 0 3 3 0 4 0]
test_29_caption 16
[3 1 3 2 3 3 1 1 0 3 1 2 1 0 1 1]
test_20_caption 60
[ 7 13 13 11 11 10  6  3  6  1 11  2  6  4  6 10 10  3  3  3  4 13  6  3
 11  4  3  4  6  3  1  8  1  4 12 13  8  2  0 11  6  9  1  0 11  4  0 12
 10  8  2 11  1 10 14  1  5  4 11  0]
test_19_caption 14
[0 0 0 2 0 0 1 2 1 2 1 1 0 2]
test_24_caption 17
[3 3 1 1 2 0 2 1 2 0 1 0 2 2 0 1 1]
test_12_caption 23
[1 4 0 1 0 2 4 2 1 2 1 1 1 2 1 4 3 2 1 1 1 1 0]
test_15_caption 18
[0 0 0 3 0 2 1 1 2 2 1 2 0 0 2 2 0 1]
test_14_caption 16
[2 2 3 0 0 1 2 2 2 1 0 0 0 1 



---

데이터프레임에 입력

---

In [69]:

for json_file in json_files:

    json_dic[json_file]['cluster_by_time']=outputs_dic[json_file[10:-5]]
    json_dic[json_file]['cluster_by_sentence']=outputs_sentence_dic[json_file[10:-5]]

#클러스터 별로 다시 태깅을 해봅시다~?

In [70]:
def komoran_tokenizer(sent):
    words = komoran.pos(sent, join=True)
    words = [w for w in words if (('/NN' in w or '/VV' in w) and '여자' not in w and '남자' not in w and '앉' not in w and '얼굴' not in w and 'NNB' not in w and 'NNP' not in w)]#or '/XR' in w or '/VA' in w or '/VV' in w)]
    
    return words

In [71]:
summarizer = KeywordSummarizer(tokenize=komoran_tokenizer, min_count=1, min_cooccurrence=1)
kmeans_komoran_words={}
for json_file in json_files:
    words={}
    for cluster in kmeans_dic[json_file[10:-5]]:
        sents = kmeans_dic[json_file[10:-5]][cluster]
        #print(sents)
        words[cluster]=(summarizer.summarize(sents, topk=50))
    kmeans_komoran_words[json_file[10:-5]]=words

In [72]:
kmeans_caption_words={}

for json_file in json_files:
    new_words_dic={}
    for cluster in kmeans_komoran_words[json_file[10:-5]]:
        new_words=[]
        for word, rank in kmeans_komoran_words[json_file[10:-5]][cluster]:
            word_split = word.split('/')
            if (word_split[1]!='VV'):
                new_words.append(word_split[0])
        new_words_dic[cluster]=new_words
    kmeans_caption_words[json_file[10:-5]]=new_words_dic

In [84]:
kmeans_caption_tags = {}

for json_file in json_files:
    letters_dic={}
    for cluster in kmeans_caption_words[json_file[10:-5]]:
        letters = []
        for word in kmeans_caption_words[json_file[10:-5]][cluster]:

            if word in ['자동차', '차','운전']:
                letters.append('드라이브')
            
            elif word in ['거리','걷']:
                letters+=['산책','일상']
                # letters.append('산책')
                # letters.append('일상')
            elif '바다' ==word:
                letters+=['휴양지','여행','청량한']
                # letters.append('휴양지')
                # letters.append('여행')
                # letters.append('청량한')

            elif word in ['그릇','음식']:
                letters+=['요리','레스토랑']
                # letters.append('요리')
                # letters.append('레스토랑')
                
            elif word in ['개','강아지','고양이']:
                letters+=['반려동물','힐']
                # letters.append('반려동물')
                # letters.append('힐링')

            elif word in ['피아노', '바이올린']:
                letters.append(word)
            elif word in ['운동','탁구', '공','축구','농구','배드민턴','테니스','라켓']:
                letters.append('운동')
            elif word =='카메라':
                letters.append('브이로그')
            elif word=='춤':
                letters+=['내적댄스','신나는','기분전환']
            elif word =='연주':
                letters.append('공연')
                # letters.append('내적댄스')
                # letters.append('신나는')
                # letters.append('기분전환')
        letters = list(set(letters))
        letters+=kmeans_caption_words[json_file[10:-5]][cluster]
        letters_dic[cluster]=letters
    kmeans_caption_tags[json_file[10:-5]]=letters_dic

In [85]:
for json_file in json_files:
    print(kmeans_caption_tags[json_file[10:-5]])

{4: ['그룹', '사람', '의자'], 1: ['손', '아기', '소녀', '의자'], 2: ['브이로그', '아기', '바닥', '손', '의자', '이야기', '카메라', '흰색'], 0: ['아기', '아이', '바닥'], 3: ['브이로그', '아기', '의자', '이야기', '카메라']}
{2: ['사람', '강', '주위', '지역', '그룹'], 1: ['브이로그', '말', '카메라', '손'], 4: ['인도', '앞', '주위', '무대', '사람'], 3: ['브이로그', '카메라', '말', '말하기', '의자'], 0: ['재생', '무대'], 5: ['사람', '건물', '그룹', '표시']}
{0: ['브이로그', '카메라', '방', '이야기', '말'], 2: ['브이로그', '방', '흰색', '시작', '청소', '이야기', '카메라', '면도칼'], 1: ['브이로그', '칼', '사람', '말', '카메라', '동안', '인도', '흰색']}
{0: ['레스토랑', '브이로그', '요리', '카메라', '병', '말', '음식', '칼', '의자', '인도', '이야기'], 1: ['드라이브', '차', '의자']}
{6: ['브이로그', '말', '카메라'], 5: ['브이로그', '이야기', '카메라'], 3: ['레스토랑', '요리', '흰색', '컵', '부엌', '음식'], 2: ['감자', '옆', '손'], 1: ['브이로그', '이야기', '카메라'], 4: ['레스토랑', '요리', '손', '미소', '감자', '음식', '의자'], 0: ['부엌'], 7: ['브이로그', '위', '아이', '이야기', '카메라']}
{2: ['브이로그', '카메라', '아기', '무릎', '아이', '표시', '말', '단어', '흰색', '얘기'], 0: ['브이로그', '이야기', '카메라', '아기', '의자', '조각'], 1: ['아기', '위', '아이']}
{1: ['내적댄스', '신나는', '기분전

#tag별로 음악을 뽑아보기

In [86]:
music_df.head()

tags  ...                updt_date
0                                                [락]  ...  2013-12-19 18:36:19.000
1                                           [추억, 회상]  ...  2014-12-02 16:19:42.000
2                                          [까페, 잔잔한]  ...  2017-08-28 07:09:34.000
3  [연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...  ...  2019-12-05 15:15:18.000
4                                               [댄스]  ...  2011-10-25 13:54:56.000

[5 rows x 6 columns]

In [87]:
music_df.dtypes

tags            object
id               int64
plylst_title    object
songs           object
like_cnt         int64
updt_date       object
dtype: object

In [108]:
tag_df = pd.DataFrame(columns = music_df.columns )
#first_tag=first_tag.append(music_df.iloc[0])
tag_df.head()

Empty DataFrame
Columns: [tags, id, plylst_title, songs, like_cnt, updt_date]
Index: []

In [109]:
tag_dic= {}
for json_file in json_files:
    tag_dic[json_file[10:-5]]={}

for json_file in json_files:
    for cluster in kmeans_caption_tags[json_file[10:-5]]:
        tag_dic[json_file[10:-5]][cluster]=pd.DataFrame(columns = music_df.columns)


In [110]:
new_music_df = music_df[(music_df['like_cnt'])>100]

In [111]:
len(new_music_df), len(music_df)

(13909, 115071)

In [112]:
for json_file in json_files:
    print(json_file[10:-5])
    for cluster in kmeans_caption_tags[json_file[10:-5]]:
        print(kmeans_caption_tags[json_file[10:-5]][cluster][:5])

test_22_caption
['그룹', '사람', '의자']
['손', '아기', '소녀', '의자']
['브이로그', '아기', '바닥', '손', '의자']
['아기', '아이', '바닥']
['브이로그', '아기', '의자', '이야기', '카메라']
test_30_caption
['사람', '강', '주위', '지역', '그룹']
['브이로그', '말', '카메라', '손']
['인도', '앞', '주위', '무대', '사람']
['브이로그', '카메라', '말', '말하기', '의자']
['재생', '무대']
['사람', '건물', '그룹', '표시']
test_16_caption
['브이로그', '카메라', '방', '이야기', '말']
['브이로그', '방', '흰색', '시작', '청소']
['브이로그', '칼', '사람', '말', '카메라']
test_28_caption
['레스토랑', '브이로그', '요리', '카메라', '병']
['드라이브', '차', '의자']
test_18_caption
['브이로그', '말', '카메라']
['브이로그', '이야기', '카메라']
['레스토랑', '요리', '흰색', '컵', '부엌']
['감자', '옆', '손']
['브이로그', '이야기', '카메라']
['레스토랑', '요리', '손', '미소', '감자']
['부엌']
['브이로그', '위', '아이', '이야기', '카메라']
test_13_caption
['브이로그', '카메라', '아기', '무릎', '아이']
['브이로그', '이야기', '카메라', '아기', '의자']
['아기', '위', '아이']
test_21_caption
['내적댄스', '신나는', '기분전환', '공연', '무대']
['내적댄스', '신나는', '기분전환', '춤', '앞']
['내적댄스', '신나는', '기분전환', '춤', '방']
['내적댄스', '신나는', '기분전환', '방', '그룹']
test_17_caption
['레스토랑', '요리', '음식

In [113]:
#18min
for i in range(len(new_music_df)):
    if i%100==99:
        print(i)
    for json_file in json_files:
        for cluster in kmeans_caption_tags[json_file[10:-5]]:
            inter = list(set(kmeans_caption_tags[json_file[10:-5]][cluster][:5]).intersection(new_music_df.iloc[i]['tags']))
            count = len(inter)
            # for tag in music_df.iloc[i]['tags']:
            #     if tag in kmeans_caption_tags[json_file[10:-5]][cluster]:
            #         count+=1
            if count :
                tag_dic[json_file[10:-5]][cluster]=tag_dic[json_file[10:-5]][cluster].append(new_music_df.iloc[i])
                tag_dic[json_file[10:-5]][cluster]['count']=count


99
199
299
399
499
599
699
799
899
999
1099
1199
1299
1399
1499
1599
1699
1799
1899
1999
2099
2199
2299
2399
2499
2599
2699
2799
2899
2999
3099
3199
3299
3399
3499
3599
3699
3799
3899
3999
4099
4199
4299
4399
4499
4599
4699
4799
4899
4999
5099
5199
5299
5399
5499
5599
5699
5799
5899
5999
6099
6199
6299
6399
6499
6599
6699
6799
6899
6999
7099
7199
7299
7399
7499
7599
7699
7799
7899
7999
8099
8199
8299
8399
8499
8599
8699
8799
8899
8999
9099
9199
9299
9399
9499
9599
9699
9799
9899
9999
10099
10199
10299
10399
10499
10599
10699
10799
10899
10999
11099
11199
11299
11399
11499
11599
11699
11799
11899
11999
12099
12199
12299
12399
12499
12599
12699
12799
12899
12999
13099
13199
13299
13399
13499
13599
13699
13799
13899


In [136]:
for json_file in json_files:
    print(json_file[10:-5])
    for cluster in kmeans_caption_tags[json_file[10:-5]]:
        print(kmeans_caption_tags[json_file[10:-5]][cluster])
        print(tag_dic[json_file[10:-5]][cluster].shape)

test_22_caption
['그룹', '사람', '의자']
(3, 7)
['손', '아기', '소녀', '의자']
(21, 7)
['브이로그', '아기', '바닥', '손', '의자', '이야기', '카메라', '흰색']
(25, 7)
['아기', '아이', '바닥']
(21, 7)
['브이로그', '아기', '의자', '이야기', '카메라']
(25, 7)
test_30_caption
['사람', '강', '주위', '지역', '그룹']
(4, 7)
['브이로그', '말', '카메라', '손']
(6, 7)
['인도', '앞', '주위', '무대', '사람']
(1, 7)
['브이로그', '카메라', '말', '말하기', '의자']
(5, 7)
['재생', '무대']
(0, 6)
['사람', '건물', '그룹', '표시']
(3, 7)
test_16_caption
['브이로그', '카메라', '방', '이야기', '말']
(7, 7)
['브이로그', '방', '흰색', '시작', '청소', '이야기', '카메라', '면도칼']
(38, 7)
['브이로그', '칼', '사람', '말', '카메라', '동안', '인도', '흰색']
(6, 7)
test_28_caption
['레스토랑', '브이로그', '요리', '카메라', '병', '말', '음식', '칼', '의자', '인도', '이야기']
(16, 7)
['드라이브', '차', '의자']
(1587, 7)
test_18_caption
['브이로그', '말', '카메라']
(5, 7)
['브이로그', '이야기', '카메라']
(6, 7)
['레스토랑', '요리', '흰색', '컵', '부엌', '음식']
(11, 7)
['감자', '옆', '손']
(1, 7)
['브이로그', '이야기', '카메라']
(6, 7)
['레스토랑', '요리', '손', '미소', '감자', '음식', '의자']
(12, 7)
['부엌']
(0, 6)
['브이로그', '위', '아이', '이야기', '카메라']
(8, 7)
t

In [115]:
kmeans_caption_tags[json_file[10:-5]][cluster]

['레스토랑', '요리', '부엌', '사람', '인도', '그릇', '물']

In [119]:
tag_dic[json_file[10:-5]][cluster].head(20)

tags  ... count
7003          [카페, 연주곡, 잔잔한, 청소, 연인, 여행, 집, 요리, 감성적인, 오후]  ...     1
12774          [매장, 매장음악, 레스토랑, 추억, 드라이브, 펍, 맥주, 펑키, 디스코]  ...     1
14929   [휴식, 카페, 잔잔한, 레스토랑, 클래식, 라운지, 기분전환, 뉴에이지, 힐링, 호텔]  ...     1
19455        [분위기, 카페, 레스토랑, Jazz, 재즈, 저음질, 올드팝, 와인, 로파이]  ...     1
45493            [LOVE, 밤, 로맨틱, 레스토랑, 분위기, 재즈, 고백, 사랑, 팝]  ...     1
54348            [연말, 연주곡, 낭만, 힐링, 크리스마스, 캐롤, 레스토랑, 캐롤연주]  ...     1
63129      [집중, 라운지, 아침, 레스토랑, 매장, 모닝콜, 독서, 피아노, 미술관, 호텔]  ...     1
63136                                  [요리, 휴식, 뉴에이지, 재즈]  ...     1
75593      [우울, 힘들때, 인간관계, 위로, 사람, 사회생활, 학교, 친구, 회사, 외로움]  ...     1
90323   [우아한, 연주곡, 레스토랑, 오후, 클래식, 저녁식사, 저녁, 로맨틱한, 레스토랑...  ...     1
102203                           [Lounge, 레스토랑, 매장음악, 카페]  ...     1
104180           [카페, 연주곡, 잔잔한, 레스토랑, 분위기, 클래식, 고급진, 편안한]  ...     1

[12 rows x 7 columns]

In [117]:
songs_dic={}

In [120]:
for json_file in json_files:
    songs={}
    for cluster in kmeans_caption_tags[json_file[10:-5]]:
        print(json_file[10:-5])
        try:
            grouped = tag_dic[json_file[10:-5]][cluster].groupby('count')
            max_key =max(list(grouped.groups.keys()))
            print(max_key)

            for key, group in grouped:
                if key == max_key:
                    # print("* key", key)
                    # print("* count", len(group))
                    # print(group.head())
                    # print('\n')
                    songs[cluster] = group
                    # print(plylst_df.head())
                    break
        except:
            print("ERROR")
            songs[cluster]=tag_dic[json_file[10:-5]][cluster]
            
    songs_dic[json_file[10:-5]]=songs

test_22_caption
1
test_22_caption
1
test_22_caption
1
test_22_caption
1
test_22_caption
1
test_30_caption
1
test_30_caption
1
test_30_caption
1
test_30_caption
1
test_30_caption
ERROR
test_30_caption
1
test_16_caption
1
test_16_caption
1
test_16_caption
1
test_28_caption
1
test_28_caption
1
test_18_caption
1
test_18_caption
1
test_18_caption
1
test_18_caption
1
test_18_caption
1
test_18_caption
1
test_18_caption
ERROR
test_18_caption
1
test_13_caption
1
test_13_caption
1
test_13_caption
1
test_21_caption
1
test_21_caption
1
test_21_caption
1
test_21_caption
1
test_17_caption
1
test_17_caption
1
test_17_caption
1
test_17_caption
ERROR
test_17_caption
ERROR
test_29_caption
1
test_29_caption
1
test_29_caption
ERROR
test_29_caption
1
test_20_caption
1
test_20_caption
ERROR
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test_20_caption
1
test

In [121]:
##TIME SECTIONS ##
##START & END ##

sections = {}
for json_file in json_files:
    grouped=json_dic[json_file].groupby(json_dic[json_file]['cluster_by_time'])
    sect = {}
    for key, group in grouped:
        start = round(group['start'].median(),2)
        end = round(group['end'].median(),2)
        sect[key] = {'start':start,'end':end}
    sections[json_file[10:-5]]=sect                 

In [122]:
for json_file in json_files: 
    for cluster in songs_dic[json_file[10:-5]]:
        songs_dic[json_file[10:-5]][cluster]['like_cnt'] =songs_dic[json_file[10:-5]][cluster]['like_cnt'].astype(float)
        #print(songs_dic[json_file[10:-5]][cluster]['like_cnt'].head(10))
        songs_dic[json_file[10:-5]][cluster] = songs_dic[json_file[10:-5]][cluster][songs_dic[json_file[10:-5]][cluster]['like_cnt'] >100.0]
        print(songs_dic[json_file[10:-5]][cluster]['like_cnt'].head(10))

18172    155.0
43031    398.0
75593    417.0
Name: like_cnt, dtype: float64
4561     177.0
5969     124.0
11449    157.0
12751    335.0
29566    158.0
32085    382.0
35976    196.0
40366    442.0
42896    193.0
46221    680.0
Name: like_cnt, dtype: float64
4561      177.0
5969      124.0
11449     157.0
12751     335.0
29566     158.0
32085     382.0
40366     442.0
42896     193.0
46221     680.0
49447    1060.0
Name: like_cnt, dtype: float64
4561      177.0
5969      124.0
11449     157.0
12751     335.0
32085     382.0
40366     442.0
42896     193.0
46221     680.0
49447    1060.0
49959     106.0
Name: like_cnt, dtype: float64
4561      177.0
5969      124.0
11449     157.0
12751     335.0
26505     365.0
32085     382.0
40366     442.0
42896     193.0
46221     680.0
49447    1060.0
Name: like_cnt, dtype: float64
18172    155.0
37148    117.0
43031    398.0
75593    417.0
Name: like_cnt, dtype: float64
29566     158.0
54177     312.0
57125     333.0
70913     570.0
92614     293.0

In [126]:
contains_vlog =music_df['plylst_title'].str.contains("브이로그")
subset_df = music_df[contains_vlog]

In [127]:
default_song_list = subset_df.sort_values(by=['like_cnt'],axis=0,ascending=False).iloc[2]['songs']

In [129]:
import random
songs_tag = {}


sections = {}
for json_file in json_files:
    grouped=json_dic[json_file].groupby(json_dic[json_file]['cluster_by_time'])
    sect = {}
    for key, group in grouped:
        start = round(group['start'].median(),2)
        end = round(group['end'].median(),2)
        sect[key] = {'start':start,'end':end}
    sections[json_file[10:-5]]=sect  



for json_file in json_files:
    cluster_songs=[]
    song_list = default_song_list
    for cluster in songs_dic[json_file[10:-5]]:
        plyst = 0
        try: plyst = random.randrange(0,len(songs_dic[json_file[10:-5]][cluster]))
        except:
            continue
        try:
            song_list = songs_dic[json_file[10:-5]][cluster].sort_values(by=['like_cnt'], axis=0, ascending=False).iloc[plyst]['songs']
            print(songs_dic[json_file[10:-5]][cluster].sort_values(by=['like_cnt'], axis=0, ascending=False).iloc[plyst]['plylst_title'])
        except:
            print("EMPTY at ",json_file[10:-5],cluster)
            #song_list = default_song_list
        song = song_list[random.randrange(1,len(song_list))]
        cluster_songs.append(song)
        sections[json_file[10:-5]][cluster]['song_id'] = song
    songs_tag[json_file[10:-5]]=cluster_songs

국내 여성 인디&포크 듀엣/그룹은 누구?!
잠못드는 밤, 너도 나도 울었네 (널 위한 자장가)
우리아기 귀성길 출동이다! ♥핑크퐁♥ 뚜루루뚜루~
푸카푸카! 울 예쁜 아들램, 딸램 목욕할 시간이에요♥
태교와 태아에 좋은 음악모음 2_동요태교
국내 여성 인디&포크 듀엣/그룹은 누구?!
한강 브이로그, 한강에서 여유로운 일상을 담은 Vlog BGM
#21 인간관계 내 맘 같지않더라도  우리 상처받지 말아요 (전체재생)
감각적인 영상을 위한 독특한 음악 추천
#21 인간관계 내 맘 같지않더라도  우리 상처받지 말아요 (전체재생)
여행 영상 만들 때 쓰고 싶어! 설렘 가득 BGM
Good Morning! 상쾌한 아침을 깨우는 올드팝
감각적인 영상을 위한 독특한 음악 추천
호텔로비에서 들려오는 클래식음악들
감각적이고 센스 충만한 트렌디한 POP을 골라봤어.
감각적인 영상을 위한 독특한 음악 추천
한강 브이로그, 한강에서 여유로운 일상을 담은 Vlog BGM
빈티지함 그대로 공간감이 느껴지는 JAZZ
카리브의 열정과 아프로 리듬의 아찔한 결합! 쿠바의 대중음악, 손
여행을 뮤직비디오로 만들어줄 청량감 가득한 팝!! #밴드 사운드
[4/20] 70년대 미국 햄버거 가게 온 듯한 음악! (#소울펑키)
감각적인 영상을 위한 독특한 음악 추천
아기에게 들려주는 ASMR: For Babies
아기를 위한 태교 클래식-Piano
꿈나라로 여행하는 Choral Music
힙합,힙존 노래 모음
프렌치 터치의 펑키함! 프렌치 하우스
멈출 수 없어! 귀를 사로잡는 비트의 힙합/R&B Vol.4
김은숙 작가의 드라마 OST 모음!!
호텔 라운지, 고급레스토랑에 어울리는  잔잔한 뉴에이지+클래식;)
호텔로비에서 들려오는 클래식음악들
식욕 자극을 위한 ASMR: Eating Sounds
#21 인간관계 내 맘 같지않더라도  우리 상처받지 말아요 (전체재생)
우리집 고양이 골골송 부르게 할 편안한 음악 - 고양이를 위한 클래식
강아지가 좋아하는 음악 (피아노 연주곡)
여름을 맞이하는 방법 - 시원

In [180]:
sections['test_1_caption']

{0: {'end': 31.2, 'song_id': 660013, 'start': 2.6},
 1: {'end': 299.95, 'song_id': 463542, 'start': 279.8},
 2: {'end': 122.45, 'song_id': 406621, 'start': 102.15}}

In [130]:
import json

with open("music_tags.json", "w") as json_file:

    json.dump(sections, json_file,indent=4,sort_keys=True)


In [174]:
# new_json={}
# with open("music_tags.json") as json_file:

#     new_json = json.load(json_file)


In [179]:
# new_json['test_1_caption']

{'0': {'end': 31.2, 'song_id': 660013, 'start': 2.6},
 '1': {'end': 299.95, 'song_id': 463542, 'start': 279.8},
 '2': {'end': 122.45, 'song_id': 406621, 'start': 102.15}}

#망한 DBSCAN

In [ ]:
# dbscan_dic = {}

# for json_file in json_files:
#     db={}
#     n_points = len(emb_sents[json_file[10:-5]])
#     d = 384
#     t = time.time()
#     output = DBSCAN(eps=0.3, min_samples=2).fit(emb_sents[json_file[10:-5]])
#     print('-'*40)
#     print(json_file[10:-5])
#     print(output.labels_)
#     print(sentences[json_file[10:-5]])
#     for i in output.labels_: #initialize
#         db[i]=[]

#     for i in range(len(output.labels_)):
#         db[output.labels_[i]].append(sentences[json_file[10:-5]][i])
#     dbscan_dic[json_file[10:-5]] = db


In [ ]:
# for json_file in json_files:
#     n_points = len(startend[json_file[10:-5]])
#     d = 2
#     t = time.time()
#     output = DBSCAN(eps=1, min_samples=2).fit(startend[json_file[10:-5]])

#     print(output.labels_)
#     print(startend[json_file[10:-5]])
# # res = faiss.StandardGpuResources()
# # flat_config = faiss.GpuIndexFlatConfig()
# # flat_config.device = 0
# # index = faiss.GpuIndexFlatL2(res, d, flat_config)
# # index.add(X)
# # gd = GpuDbscan(X, gpu_index=index)
# # cluster_ids, core_point_flag, visited_flag = gd.gpu_dbscan(1, 10)
# # print(np.unique(cluster_ids))

In [ ]:
# for json_file in json_files:
#     D= 2
#     N = int(len(startend[json_file[10:-5]]))
#     K = 3  # The number of clusters
#     X = startend[json_file[10:-5]]
#     print(json_file[10:-5], N)
#     # Setup
#     kmeans = faiss.Kmeans(d=D, k=K, niter=5, verbose=True)
#     # For GPU(s), run the following line. This will use all GPUs
#     # kmeans = faiss.Kmeans(d=D, k=K, niter=20, verbose=True, gpu=True)

#     # Run clustering
#     kmeans.train(X)

#     # Error for each iteration
#     print('error?',kmeans.obj)  # array with 20 elements

#     # Centroids after clustering
#     print('centeroids', kmeans.centroids.shape)  # (10, 128)

#     # The assignment for each vector.
#     dists, ids = kmeans.index.search(X, 1)  # Need to run NN search again
#     print('ids shape',ids.shape)  # (10000, 1)
#     print(ids.flatten())
#     # Params
#     print("D:", kmeans.d)
#     print("K:", kmeans.k)
#     print("niter:", kmeans.cp.niter)